### ISSUE TITLE
Mobile above-the-fold

### ISSUE THREAD

**Issue by rashedaleecom** [rashedaleecom/Radiant-Marketing#9]
The elements in the front page are a little misaligned. See image. 

Also, we might want to move all the elements further to the right (green line). 

**URL tested:** https://porttech-4499320.hs-sites.com/home

Open [URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+X&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fporttech-4499320.hs-sites.com%2Fhome&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://porttech-4499320.hs-sites.com/home) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | iPhone X |
| Browser | Mobile_safari |
| Operating System | iOS 11.0 |
| Resolution | 1125 x 2436 px |
| Screen size | 5.8 in - 2.79 x 5.65 in |
| Viewport | 375 x 812 dp |
| Aspect Ratio | 19.5 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/dcdc44f5818ee053ae7bd86676be450c26fda7f0/realios_iPhone_X.jpg)![Screenshot URL](https://live.browserstack.com/issue-tracker/dcdc44f5818ee053ae7bd86676be450c26fda7f0/realios_iPhone_X.jpg)

**Click [this URL](https://live.browserstack.com/dashboard#os=iOS&os_version=11.0&device=iPhone+X&device_browser=safari&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fporttech-4499320.hs-sites.com%2Fhome&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://porttech-4499320.hs-sites.com/home) to reproduce the issue on Browserstack:**

**Comment by computan** [comment]
Done
